# Generated by Django 5.1.7 on 2025-03-21 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('mobile', models.IntegerField()),
                ('massege', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('art_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artglarry.artist')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artglarry.register')),
            ],
        ),
    ]
