# Generated by Django 5.1.7 on 2025-03-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0002_contact_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ImageField(upload_to='img/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='atist_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='sold',
            name='contact',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sold',
            name='art_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='artglarry.art'),
        ),
        migrations.AddField(
            model_name='art',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artglarry.atist_register'),
        ),
        migrations.CreateModel(
            name='user_bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('artist_art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artglarry.art')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artglarry.register')),
            ],
        ),
        migrations.DeleteModel(
            name='artist',
        ),
    ]
