# Generated by Django 5.1.7 on 2025-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0003_art_atist_register_rename_name_register_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
