# Generated by Django 5.1.7 on 2025-03-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0004_art_art_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bid',
            name='artist_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artglarry.art'),
        ),
    ]
