# Generated by Django 5.1.7 on 2025-03-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0006_alter_art_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='status',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artglarry.atist_register'),
        ),
    ]
