# Generated by Django 5.1.7 on 2025-03-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0007_art_status_alter_art_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='art_by',
        ),
        migrations.AddField(
            model_name='sold',
            name='art',
            field=models.ImageField(default=None, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sold',
            name='artist_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='artglarry.atist_register'),
            preserve_default=False,
        ),
    ]
