# Generated by Django 5.1.7 on 2025-04-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0008_remove_sold_art_by_sold_art_sold_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atist_register',
            name='contact',
        ),
    ]
