# Generated by Django 5.1.7 on 2025-04-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0009_remove_atist_register_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='atist_register',
            new_name='artist_register',
        ),
    ]
