# Generated by Django 5.1.7 on 2025-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artglarry', '0010_rename_atist_register_artist_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(),
        ),
    ]
